// <auto-generated>
//   Generated by tools/generate-publishers.py from the `dbn` crate's publishers.rs
//   (crate version 0.68.0). Do not hand-edit.
//   Regenerate with: python3 tools/generate-publishers.py <path-to-publishers.rs>
// </auto-generated>

#nullable enable

namespace DatabentoDotNet.Dbn.Publishers;

/// <summary>A specific Venue from a specific data source.</summary>
/// <remarks>
/// Mechanically derived from the <c>dbn</c> crate's <c>publishers.rs</c> (v0.68.0) by <c>tools/generate-publishers.py</c>. 145 variants, contiguous <c>1..145</c>. Upstream marks this type <c>#[non_exhaustive]</c>; there is no default (zero) variant. See <see cref="PublisherWireStrings"/> for wire-string conversions and <see cref="PublisherMappings"/> for the mapping to and from its <see cref="Venue"/> and <see cref="Dataset"/>.
/// </remarks>
public enum Publisher : ushort
{
    /// <summary>CME Globex MDP 3.0</summary>
    GlbxMdp3Glbx = 1,

    /// <summary>Nasdaq TotalView-ITCH</summary>
    XnasItchXnas = 2,

    /// <summary>Nasdaq Texas TotalView-ITCH</summary>
    XbosItchXbos = 3,

    /// <summary>Nasdaq PSX TotalView-ITCH</summary>
    XpsxItchXpsx = 4,

    /// <summary>Cboe BZX Depth</summary>
    BatsPitchBats = 5,

    /// <summary>Cboe BYX Depth</summary>
    BatyPitchBaty = 6,

    /// <summary>Cboe EDGA Depth</summary>
    EdgaPitchEdga = 7,

    /// <summary>Cboe EDGX Depth</summary>
    EdgxPitchEdgx = 8,

    /// <summary>NYSE Integrated</summary>
    XnysPillarXnys = 9,

    /// <summary>NYSE National Integrated</summary>
    XcisPillarXcis = 10,

    /// <summary>NYSE American Integrated</summary>
    XasePillarXase = 11,

    /// <summary>NYSE Texas Integrated</summary>
    XchiPillarXchi = 12,

    /// <summary>NYSE National BBO</summary>
    XcisBboXcis = 13,

    /// <summary>NYSE National Trades</summary>
    XcisTradesXcis = 14,

    /// <summary>MEMX MEMOIR Depth</summary>
    MemxMemoirMemx = 15,

    /// <summary>MIAX Pearl Depth</summary>
    EprlDomEprl = 16,

    /// <summary>FINRA/Nasdaq TRF Carteret</summary>
    XnasNlsFinn = 17,

    /// <summary>FINRA/Nasdaq TRF Chicago</summary>
    XnasNlsFinc = 18,

    /// <summary>FINRA/NYSE TRF</summary>
    XnysTradesFiny = 19,

    /// <summary>OPRA - NYSE American Options</summary>
    OpraPillarAmxo = 20,

    /// <summary>OPRA - BOX Options</summary>
    OpraPillarXbox = 21,

    /// <summary>OPRA - Cboe Options</summary>
    OpraPillarXcbo = 22,

    /// <summary>OPRA - MIAX Emerald</summary>
    OpraPillarEmld = 23,

    /// <summary>OPRA - Cboe EDGX Options</summary>
    OpraPillarEdgo = 24,

    /// <summary>OPRA - Nasdaq GEMX</summary>
    OpraPillarGmni = 25,

    /// <summary>OPRA - Nasdaq ISE</summary>
    OpraPillarXisx = 26,

    /// <summary>OPRA - Nasdaq MRX</summary>
    OpraPillarMcry = 27,

    /// <summary>OPRA - MIAX Options</summary>
    OpraPillarXmio = 28,

    /// <summary>OPRA - NYSE Arca Options</summary>
    OpraPillarArco = 29,

    /// <summary>OPRA - Options Price Reporting Authority</summary>
    OpraPillarOpra = 30,

    /// <summary>OPRA - MIAX Pearl</summary>
    OpraPillarMprl = 31,

    /// <summary>OPRA - Nasdaq Options</summary>
    OpraPillarXndq = 32,

    /// <summary>OPRA - Nasdaq Texas Options</summary>
    OpraPillarXbxo = 33,

    /// <summary>OPRA - Cboe C2 Options</summary>
    OpraPillarC2Ox = 34,

    /// <summary>OPRA - Nasdaq PHLX</summary>
    OpraPillarXphl = 35,

    /// <summary>OPRA - Cboe BZX Options</summary>
    OpraPillarBato = 36,

    /// <summary>OPRA - MEMX Options</summary>
    OpraPillarMxop = 37,

    /// <summary>IEX TOPS</summary>
    IexgTopsIexg = 38,

    /// <summary>DBEQ Basic - NYSE Texas</summary>
    DbeqBasicXchi = 39,

    /// <summary>DBEQ Basic - NYSE National</summary>
    DbeqBasicXcis = 40,

    /// <summary>DBEQ Basic - IEX</summary>
    DbeqBasicIexg = 41,

    /// <summary>DBEQ Basic - MIAX Pearl</summary>
    DbeqBasicEprl = 42,

    /// <summary>NYSE Arca Integrated</summary>
    ArcxPillarArcx = 43,

    /// <summary>NYSE BBO</summary>
    XnysBboXnys = 44,

    /// <summary>NYSE Trades</summary>
    XnysTradesXnys = 45,

    /// <summary>Nasdaq QBBO</summary>
    XnasQbboXnas = 46,

    /// <summary>Nasdaq Trades</summary>
    XnasNlsXnas = 47,

    /// <summary>Databento US Equities Plus - NYSE Texas</summary>
    EqusPlusXchi = 48,

    /// <summary>Databento US Equities Plus - NYSE National</summary>
    EqusPlusXcis = 49,

    /// <summary>Databento US Equities Plus - IEX</summary>
    EqusPlusIexg = 50,

    /// <summary>Databento US Equities Plus - MIAX Pearl</summary>
    EqusPlusEprl = 51,

    /// <summary>Databento US Equities Plus - Nasdaq</summary>
    EqusPlusXnas = 52,

    /// <summary>Databento US Equities Plus - NYSE</summary>
    EqusPlusXnys = 53,

    /// <summary>Databento US Equities Plus - FINRA/Nasdaq TRF Carteret</summary>
    EqusPlusFinn = 54,

    /// <summary>Databento US Equities Plus - FINRA/NYSE TRF</summary>
    EqusPlusFiny = 55,

    /// <summary>Databento US Equities Plus - FINRA/Nasdaq TRF Chicago</summary>
    EqusPlusFinc = 56,

    /// <summary>ICE Europe Commodities</summary>
    IfeuImpactIfeu = 57,

    /// <summary>ICE Endex</summary>
    NdexImpactNdex = 58,

    /// <summary>Databento US Equities Basic - Consolidated</summary>
    DbeqBasicDbeq = 59,

    /// <summary>EQUS Plus - Consolidated</summary>
    EqusPlusEqus = 60,

    /// <summary>OPRA - MIAX Sapphire</summary>
    OpraPillarSphr = 61,

    /// <summary>Databento US Equities (All Feeds) - NYSE Texas</summary>
    EqusAllXchi = 62,

    /// <summary>Databento US Equities (All Feeds) - NYSE National</summary>
    EqusAllXcis = 63,

    /// <summary>Databento US Equities (All Feeds) - IEX</summary>
    EqusAllIexg = 64,

    /// <summary>Databento US Equities (All Feeds) - MIAX Pearl</summary>
    EqusAllEprl = 65,

    /// <summary>Databento US Equities (All Feeds) - Nasdaq</summary>
    EqusAllXnas = 66,

    /// <summary>Databento US Equities (All Feeds) - NYSE</summary>
    EqusAllXnys = 67,

    /// <summary>Databento US Equities (All Feeds) - FINRA/Nasdaq TRF Carteret</summary>
    EqusAllFinn = 68,

    /// <summary>Databento US Equities (All Feeds) - FINRA/NYSE TRF</summary>
    EqusAllFiny = 69,

    /// <summary>Databento US Equities (All Feeds) - FINRA/Nasdaq TRF Chicago</summary>
    EqusAllFinc = 70,

    /// <summary>Databento US Equities (All Feeds) - Cboe BZX</summary>
    EqusAllBats = 71,

    /// <summary>Databento US Equities (All Feeds) - Cboe BYX</summary>
    EqusAllBaty = 72,

    /// <summary>Databento US Equities (All Feeds) - Cboe EDGA</summary>
    EqusAllEdga = 73,

    /// <summary>Databento US Equities (All Feeds) - Cboe EDGX</summary>
    EqusAllEdgx = 74,

    /// <summary>Databento US Equities (All Feeds) - Nasdaq Texas</summary>
    EqusAllXbos = 75,

    /// <summary>Databento US Equities (All Feeds) - Nasdaq PSX</summary>
    EqusAllXpsx = 76,

    /// <summary>Databento US Equities (All Feeds) - MEMX</summary>
    EqusAllMemx = 77,

    /// <summary>Databento US Equities (All Feeds) - NYSE American</summary>
    EqusAllXase = 78,

    /// <summary>Databento US Equities (All Feeds) - NYSE Arca</summary>
    EqusAllArcx = 79,

    /// <summary>Databento US Equities (All Feeds) - Long-Term Stock Exchange</summary>
    EqusAllLtse = 80,

    /// <summary>Nasdaq Basic - Nasdaq</summary>
    XnasBasicXnas = 81,

    /// <summary>Nasdaq Basic - FINRA/Nasdaq TRF Carteret</summary>
    XnasBasicFinn = 82,

    /// <summary>Nasdaq Basic - FINRA/Nasdaq TRF Chicago</summary>
    XnasBasicFinc = 83,

    /// <summary>ICE Europe - Off-Market Trades</summary>
    IfeuImpactXoff = 84,

    /// <summary>ICE Endex - Off-Market Trades</summary>
    NdexImpactXoff = 85,

    /// <summary>Nasdaq NLS - Nasdaq Texas</summary>
    XnasNlsXbos = 86,

    /// <summary>Nasdaq NLS - Nasdaq PSX</summary>
    XnasNlsXpsx = 87,

    /// <summary>Nasdaq Basic - Nasdaq Texas</summary>
    XnasBasicXbos = 88,

    /// <summary>Nasdaq Basic - Nasdaq PSX</summary>
    XnasBasicXpsx = 89,

    /// <summary>Databento Equities Summary</summary>
    EqusSummaryEqus = 90,

    /// <summary>NYSE National Trades and BBO</summary>
    XcisTradesbboXcis = 91,

    /// <summary>NYSE Trades and BBO</summary>
    XnysTradesbboXnys = 92,

    /// <summary>Nasdaq Basic - Consolidated</summary>
    XnasBasicEqus = 93,

    /// <summary>Databento US Equities (All Feeds) - Consolidated</summary>
    EqusAllEqus = 94,

    /// <summary>Databento US Equities Mini</summary>
    EqusMiniEqus = 95,

    /// <summary>NYSE Trades - Consolidated</summary>
    XnysTradesEqus = 96,

    /// <summary>ICE Futures US</summary>
    IfusImpactIfus = 97,

    /// <summary>ICE Futures US - Off-Market Trades</summary>
    IfusImpactXoff = 98,

    /// <summary>ICE Europe Financials</summary>
    IfllImpactIfll = 99,

    /// <summary>ICE Europe Financials - Off-Market Trades</summary>
    IfllImpactXoff = 100,

    /// <summary>Eurex EOBI</summary>
    XeurEobiXeur = 101,

    /// <summary>European Energy Exchange EOBI</summary>
    XeeeEobiXeee = 102,

    /// <summary>Eurex EOBI - Off-Market Trades</summary>
    XeurEobiXoff = 103,

    /// <summary>European Energy Exchange EOBI - Off-Market Trades</summary>
    XeeeEobiXoff = 104,

    /// <summary>Cboe Futures Exchange (CFE)</summary>
    XcbfPitchXcbf = 105,

    /// <summary>Cboe Futures Exchange (CFE) - Off-Market Trades</summary>
    XcbfPitchXoff = 106,

    /// <summary>Blue Ocean ATS MEMOIR</summary>
    OceaMemoirOcea = 107,

    /// <summary>OPRA - MEMX MX2 Options</summary>
    OpraPillarMxto = 108,

    /// <summary>OPRA - IEX Options LLC</summary>
    OpraPillarIexo = 109,

    /// <summary>Cboe Global Indices Feed</summary>
    MainCgifMain = 110,

    /// <summary>US Equities SIP - NYSE American</summary>
    EqusSipXase = 111,

    /// <summary>US Equities SIP - Nasdaq Texas</summary>
    EqusSipXbos = 112,

    /// <summary>US Equities SIP - NYSE National</summary>
    EqusSipXcis = 113,

    /// <summary>US Equities SIP - Texas Stock Exchange</summary>
    EqusSipTxse = 114,

    /// <summary>US Equities SIP - 24X National Exchange</summary>
    EqusSip24Eq = 115,

    /// <summary>US Equities SIP - MIAX Pearl</summary>
    EqusSipEprl = 116,

    /// <summary>US Equities SIP - Nasdaq ISE</summary>
    EqusSipXisx = 117,

    /// <summary>US Equities SIP - Cboe EDGA</summary>
    EqusSipEdga = 118,

    /// <summary>US Equities SIP - Cboe EDGX</summary>
    EqusSipEdgx = 119,

    /// <summary>US Equities SIP - Long-Term Stock Exchange</summary>
    EqusSipLtse = 120,

    /// <summary>US Equities SIP - NYSE Texas</summary>
    EqusSipXchi = 121,

    /// <summary>US Equities SIP - NYSE</summary>
    EqusSipXnys = 122,

    /// <summary>US Equities SIP - NYSE Arca</summary>
    EqusSipArcx = 123,

    /// <summary>US Equities SIP - Nasdaq</summary>
    EqusSipXnas = 124,

    /// <summary>US Equities SIP - MEMX</summary>
    EqusSipMemx = 125,

    /// <summary>US Equities SIP - IEX</summary>
    EqusSipIexg = 126,

    /// <summary>US Equities SIP - Nasdaq PSX</summary>
    EqusSipXpsx = 127,

    /// <summary>US Equities SIP - Cboe BYX</summary>
    EqusSipBaty = 128,

    /// <summary>US Equities SIP - Cboe BZX</summary>
    EqusSipBats = 129,

    /// <summary>US Equities SIP - FINRA/Nasdaq TRF Carteret</summary>
    EqusSipFinn = 130,

    /// <summary>US Equities SIP - FINRA/NYSE TRF</summary>
    EqusSipFiny = 131,

    /// <summary>US Equities SIP - FINRA/Nasdaq TRF Chicago</summary>
    EqusSipFinc = 132,

    /// <summary>US Equities SIP - FINRA Alternative Display Facility</summary>
    EqusSipXadf = 133,

    /// <summary>US Equities SIP - CTA</summary>
    EqusSipCta = 134,

    /// <summary>US Equities SIP - UTP</summary>
    EqusSipUtp = 135,

    /// <summary>CGIF - Morgan Stanley Capital International</summary>
    MsciCgifMsci = 136,

    /// <summary>CGIF - FTSE Russell</summary>
    FtseCgifFtse = 137,

    /// <summary>CGIF - Intraday Net Asset Values</summary>
    InavCgifInav = 138,

    /// <summary>CGIF - Morning Star</summary>
    MstarCgifMstar = 139,

    /// <summary>CGIF - Crypto Currency</summary>
    CccyCgifCccy = 140,

    /// <summary>CGIF - CBOE Global Indices</summary>
    CgiCgifCgi = 141,

    /// <summary>CGIF - Definitions</summary>
    MainCgifDef = 142,

    /// <summary>JPX - Tokyo Stock Exchange</summary>
    XtksFlexXtks = 143,

    /// <summary>JPX - Tokyo Commodity Exchange</summary>
    XtktItchXtkt = 144,

    /// <summary>JPX - Osaka Exchange</summary>
    XoseItchXose = 145,
}
