// <auto-generated>
//   Generated by tools/generate-publishers.py from the `dbn` crate's publishers.rs
//   (crate version 0.68.0). Do not hand-edit.
//   Regenerate with: python3 tools/generate-publishers.py <path-to-publishers.rs>
// </auto-generated>

#nullable enable

namespace DatabentoDotNet.Dbn.Publishers;

/// <summary>
/// Validates a raw wire word against the discriminants <see cref="Publisher"/>, <see cref="Dataset"/>, and <see cref="Venue"/> actually define.
/// </summary>
/// <remarks>
/// <para>
/// What <c>EnumValues</c> is for the enums declared directly in <c>DatabentoDotNet.Dbn</c>, this is for the three declared here -- the equivalent of upstream's <c>num_enum</c>-derived <c>TryFrom&lt;u16&gt;</c> impls. They are not folded into <c>EnumValues</c> because these three tables are generated: keeping the validator beside the enum it validates means a <c>dbn</c> release bump regenerates both from one source, where a hand-maintained half in another namespace would have to be remembered.
/// </para>
/// <para>
/// <b>This is the checked conversion for <see cref="RecordHeader.PublisherId"/></b>, which is a raw <see langword="ushort"/> off the wire and is not validated on decode -- the same arrangement <see cref="RecordHeader.RawRType"/> has with <see cref="EnumValues.TryFromRType(byte, out RType)"/>. Casting an unvalidated word to <see cref="Publisher"/> and then calling <see cref="PublisherMappings.ToVenue(Publisher)"/> turns an unknown publisher into an <see cref="ArgumentOutOfRangeException"/> from deep inside a lookup; going through <see cref="TryFromPublisher"/> first makes it a <see langword="bool"/> the caller decides about.
/// </para>
/// <para>
/// Strict, like every validator in <c>EnumValues</c>: an undefined word is rejected even though upstream marks all three types <c>#[non_exhaustive]</c>. <c>#[non_exhaustive]</c> governs whether downstream Rust may exhaustively <c>match</c> the type, not whether an arbitrary word is a valid instance of it. Rejection here is the numeric out-of-range failure mode; an unrecognized wire <em>string</em> is a distinct failure handled by <see cref="PublisherWireStrings"/>.
/// </para>
/// <para>
/// One method per enum rather than a single <c>TryFrom</c> overloaded on its <see langword="out"/> parameter's type: overload resolution needs that type before it can pick an overload, so <c>out var</c> at a call site -- the ordinary way to call a <c>TryXxx</c> method -- cannot disambiguate and fails to compile. Same convention as <c>EnumValues</c> and <see cref="PublisherWireStrings"/>.
/// </para>
/// </remarks>
public static class PublisherValues
{
    // ---------------- Publisher

    /// <summary>Tries to validate <paramref name="raw"/> as a defined <see cref="Publisher"/>.</summary>
    /// <param name="raw">The raw wire word, such as <see cref="RecordHeader.PublisherId"/>.</param>
    /// <param name="value">The validated <see cref="Publisher"/>, or <see langword="default"/> when <paramref name="raw"/> is not one.</param>
    /// <returns><see langword="true"/> when <paramref name="raw"/> is a defined <see cref="Publisher"/>.</returns>
    public static bool TryFromPublisher(ushort raw, out Publisher value)
    {
        switch (raw)
        {
            case (ushort)Publisher.GlbxMdp3Glbx: value = Publisher.GlbxMdp3Glbx; return true;
            case (ushort)Publisher.XnasItchXnas: value = Publisher.XnasItchXnas; return true;
            case (ushort)Publisher.XbosItchXbos: value = Publisher.XbosItchXbos; return true;
            case (ushort)Publisher.XpsxItchXpsx: value = Publisher.XpsxItchXpsx; return true;
            case (ushort)Publisher.BatsPitchBats: value = Publisher.BatsPitchBats; return true;
            case (ushort)Publisher.BatyPitchBaty: value = Publisher.BatyPitchBaty; return true;
            case (ushort)Publisher.EdgaPitchEdga: value = Publisher.EdgaPitchEdga; return true;
            case (ushort)Publisher.EdgxPitchEdgx: value = Publisher.EdgxPitchEdgx; return true;
            case (ushort)Publisher.XnysPillarXnys: value = Publisher.XnysPillarXnys; return true;
            case (ushort)Publisher.XcisPillarXcis: value = Publisher.XcisPillarXcis; return true;
            case (ushort)Publisher.XasePillarXase: value = Publisher.XasePillarXase; return true;
            case (ushort)Publisher.XchiPillarXchi: value = Publisher.XchiPillarXchi; return true;
            case (ushort)Publisher.XcisBboXcis: value = Publisher.XcisBboXcis; return true;
            case (ushort)Publisher.XcisTradesXcis: value = Publisher.XcisTradesXcis; return true;
            case (ushort)Publisher.MemxMemoirMemx: value = Publisher.MemxMemoirMemx; return true;
            case (ushort)Publisher.EprlDomEprl: value = Publisher.EprlDomEprl; return true;
            case (ushort)Publisher.XnasNlsFinn: value = Publisher.XnasNlsFinn; return true;
            case (ushort)Publisher.XnasNlsFinc: value = Publisher.XnasNlsFinc; return true;
            case (ushort)Publisher.XnysTradesFiny: value = Publisher.XnysTradesFiny; return true;
            case (ushort)Publisher.OpraPillarAmxo: value = Publisher.OpraPillarAmxo; return true;
            case (ushort)Publisher.OpraPillarXbox: value = Publisher.OpraPillarXbox; return true;
            case (ushort)Publisher.OpraPillarXcbo: value = Publisher.OpraPillarXcbo; return true;
            case (ushort)Publisher.OpraPillarEmld: value = Publisher.OpraPillarEmld; return true;
            case (ushort)Publisher.OpraPillarEdgo: value = Publisher.OpraPillarEdgo; return true;
            case (ushort)Publisher.OpraPillarGmni: value = Publisher.OpraPillarGmni; return true;
            case (ushort)Publisher.OpraPillarXisx: value = Publisher.OpraPillarXisx; return true;
            case (ushort)Publisher.OpraPillarMcry: value = Publisher.OpraPillarMcry; return true;
            case (ushort)Publisher.OpraPillarXmio: value = Publisher.OpraPillarXmio; return true;
            case (ushort)Publisher.OpraPillarArco: value = Publisher.OpraPillarArco; return true;
            case (ushort)Publisher.OpraPillarOpra: value = Publisher.OpraPillarOpra; return true;
            case (ushort)Publisher.OpraPillarMprl: value = Publisher.OpraPillarMprl; return true;
            case (ushort)Publisher.OpraPillarXndq: value = Publisher.OpraPillarXndq; return true;
            case (ushort)Publisher.OpraPillarXbxo: value = Publisher.OpraPillarXbxo; return true;
            case (ushort)Publisher.OpraPillarC2Ox: value = Publisher.OpraPillarC2Ox; return true;
            case (ushort)Publisher.OpraPillarXphl: value = Publisher.OpraPillarXphl; return true;
            case (ushort)Publisher.OpraPillarBato: value = Publisher.OpraPillarBato; return true;
            case (ushort)Publisher.OpraPillarMxop: value = Publisher.OpraPillarMxop; return true;
            case (ushort)Publisher.IexgTopsIexg: value = Publisher.IexgTopsIexg; return true;
            case (ushort)Publisher.DbeqBasicXchi: value = Publisher.DbeqBasicXchi; return true;
            case (ushort)Publisher.DbeqBasicXcis: value = Publisher.DbeqBasicXcis; return true;
            case (ushort)Publisher.DbeqBasicIexg: value = Publisher.DbeqBasicIexg; return true;
            case (ushort)Publisher.DbeqBasicEprl: value = Publisher.DbeqBasicEprl; return true;
            case (ushort)Publisher.ArcxPillarArcx: value = Publisher.ArcxPillarArcx; return true;
            case (ushort)Publisher.XnysBboXnys: value = Publisher.XnysBboXnys; return true;
            case (ushort)Publisher.XnysTradesXnys: value = Publisher.XnysTradesXnys; return true;
            case (ushort)Publisher.XnasQbboXnas: value = Publisher.XnasQbboXnas; return true;
            case (ushort)Publisher.XnasNlsXnas: value = Publisher.XnasNlsXnas; return true;
            case (ushort)Publisher.EqusPlusXchi: value = Publisher.EqusPlusXchi; return true;
            case (ushort)Publisher.EqusPlusXcis: value = Publisher.EqusPlusXcis; return true;
            case (ushort)Publisher.EqusPlusIexg: value = Publisher.EqusPlusIexg; return true;
            case (ushort)Publisher.EqusPlusEprl: value = Publisher.EqusPlusEprl; return true;
            case (ushort)Publisher.EqusPlusXnas: value = Publisher.EqusPlusXnas; return true;
            case (ushort)Publisher.EqusPlusXnys: value = Publisher.EqusPlusXnys; return true;
            case (ushort)Publisher.EqusPlusFinn: value = Publisher.EqusPlusFinn; return true;
            case (ushort)Publisher.EqusPlusFiny: value = Publisher.EqusPlusFiny; return true;
            case (ushort)Publisher.EqusPlusFinc: value = Publisher.EqusPlusFinc; return true;
            case (ushort)Publisher.IfeuImpactIfeu: value = Publisher.IfeuImpactIfeu; return true;
            case (ushort)Publisher.NdexImpactNdex: value = Publisher.NdexImpactNdex; return true;
            case (ushort)Publisher.DbeqBasicDbeq: value = Publisher.DbeqBasicDbeq; return true;
            case (ushort)Publisher.EqusPlusEqus: value = Publisher.EqusPlusEqus; return true;
            case (ushort)Publisher.OpraPillarSphr: value = Publisher.OpraPillarSphr; return true;
            case (ushort)Publisher.EqusAllXchi: value = Publisher.EqusAllXchi; return true;
            case (ushort)Publisher.EqusAllXcis: value = Publisher.EqusAllXcis; return true;
            case (ushort)Publisher.EqusAllIexg: value = Publisher.EqusAllIexg; return true;
            case (ushort)Publisher.EqusAllEprl: value = Publisher.EqusAllEprl; return true;
            case (ushort)Publisher.EqusAllXnas: value = Publisher.EqusAllXnas; return true;
            case (ushort)Publisher.EqusAllXnys: value = Publisher.EqusAllXnys; return true;
            case (ushort)Publisher.EqusAllFinn: value = Publisher.EqusAllFinn; return true;
            case (ushort)Publisher.EqusAllFiny: value = Publisher.EqusAllFiny; return true;
            case (ushort)Publisher.EqusAllFinc: value = Publisher.EqusAllFinc; return true;
            case (ushort)Publisher.EqusAllBats: value = Publisher.EqusAllBats; return true;
            case (ushort)Publisher.EqusAllBaty: value = Publisher.EqusAllBaty; return true;
            case (ushort)Publisher.EqusAllEdga: value = Publisher.EqusAllEdga; return true;
            case (ushort)Publisher.EqusAllEdgx: value = Publisher.EqusAllEdgx; return true;
            case (ushort)Publisher.EqusAllXbos: value = Publisher.EqusAllXbos; return true;
            case (ushort)Publisher.EqusAllXpsx: value = Publisher.EqusAllXpsx; return true;
            case (ushort)Publisher.EqusAllMemx: value = Publisher.EqusAllMemx; return true;
            case (ushort)Publisher.EqusAllXase: value = Publisher.EqusAllXase; return true;
            case (ushort)Publisher.EqusAllArcx: value = Publisher.EqusAllArcx; return true;
            case (ushort)Publisher.EqusAllLtse: value = Publisher.EqusAllLtse; return true;
            case (ushort)Publisher.XnasBasicXnas: value = Publisher.XnasBasicXnas; return true;
            case (ushort)Publisher.XnasBasicFinn: value = Publisher.XnasBasicFinn; return true;
            case (ushort)Publisher.XnasBasicFinc: value = Publisher.XnasBasicFinc; return true;
            case (ushort)Publisher.IfeuImpactXoff: value = Publisher.IfeuImpactXoff; return true;
            case (ushort)Publisher.NdexImpactXoff: value = Publisher.NdexImpactXoff; return true;
            case (ushort)Publisher.XnasNlsXbos: value = Publisher.XnasNlsXbos; return true;
            case (ushort)Publisher.XnasNlsXpsx: value = Publisher.XnasNlsXpsx; return true;
            case (ushort)Publisher.XnasBasicXbos: value = Publisher.XnasBasicXbos; return true;
            case (ushort)Publisher.XnasBasicXpsx: value = Publisher.XnasBasicXpsx; return true;
            case (ushort)Publisher.EqusSummaryEqus: value = Publisher.EqusSummaryEqus; return true;
            case (ushort)Publisher.XcisTradesbboXcis: value = Publisher.XcisTradesbboXcis; return true;
            case (ushort)Publisher.XnysTradesbboXnys: value = Publisher.XnysTradesbboXnys; return true;
            case (ushort)Publisher.XnasBasicEqus: value = Publisher.XnasBasicEqus; return true;
            case (ushort)Publisher.EqusAllEqus: value = Publisher.EqusAllEqus; return true;
            case (ushort)Publisher.EqusMiniEqus: value = Publisher.EqusMiniEqus; return true;
            case (ushort)Publisher.XnysTradesEqus: value = Publisher.XnysTradesEqus; return true;
            case (ushort)Publisher.IfusImpactIfus: value = Publisher.IfusImpactIfus; return true;
            case (ushort)Publisher.IfusImpactXoff: value = Publisher.IfusImpactXoff; return true;
            case (ushort)Publisher.IfllImpactIfll: value = Publisher.IfllImpactIfll; return true;
            case (ushort)Publisher.IfllImpactXoff: value = Publisher.IfllImpactXoff; return true;
            case (ushort)Publisher.XeurEobiXeur: value = Publisher.XeurEobiXeur; return true;
            case (ushort)Publisher.XeeeEobiXeee: value = Publisher.XeeeEobiXeee; return true;
            case (ushort)Publisher.XeurEobiXoff: value = Publisher.XeurEobiXoff; return true;
            case (ushort)Publisher.XeeeEobiXoff: value = Publisher.XeeeEobiXoff; return true;
            case (ushort)Publisher.XcbfPitchXcbf: value = Publisher.XcbfPitchXcbf; return true;
            case (ushort)Publisher.XcbfPitchXoff: value = Publisher.XcbfPitchXoff; return true;
            case (ushort)Publisher.OceaMemoirOcea: value = Publisher.OceaMemoirOcea; return true;
            case (ushort)Publisher.OpraPillarMxto: value = Publisher.OpraPillarMxto; return true;
            case (ushort)Publisher.OpraPillarIexo: value = Publisher.OpraPillarIexo; return true;
            case (ushort)Publisher.MainCgifMain: value = Publisher.MainCgifMain; return true;
            case (ushort)Publisher.EqusSipXase: value = Publisher.EqusSipXase; return true;
            case (ushort)Publisher.EqusSipXbos: value = Publisher.EqusSipXbos; return true;
            case (ushort)Publisher.EqusSipXcis: value = Publisher.EqusSipXcis; return true;
            case (ushort)Publisher.EqusSipTxse: value = Publisher.EqusSipTxse; return true;
            case (ushort)Publisher.EqusSip24Eq: value = Publisher.EqusSip24Eq; return true;
            case (ushort)Publisher.EqusSipEprl: value = Publisher.EqusSipEprl; return true;
            case (ushort)Publisher.EqusSipXisx: value = Publisher.EqusSipXisx; return true;
            case (ushort)Publisher.EqusSipEdga: value = Publisher.EqusSipEdga; return true;
            case (ushort)Publisher.EqusSipEdgx: value = Publisher.EqusSipEdgx; return true;
            case (ushort)Publisher.EqusSipLtse: value = Publisher.EqusSipLtse; return true;
            case (ushort)Publisher.EqusSipXchi: value = Publisher.EqusSipXchi; return true;
            case (ushort)Publisher.EqusSipXnys: value = Publisher.EqusSipXnys; return true;
            case (ushort)Publisher.EqusSipArcx: value = Publisher.EqusSipArcx; return true;
            case (ushort)Publisher.EqusSipXnas: value = Publisher.EqusSipXnas; return true;
            case (ushort)Publisher.EqusSipMemx: value = Publisher.EqusSipMemx; return true;
            case (ushort)Publisher.EqusSipIexg: value = Publisher.EqusSipIexg; return true;
            case (ushort)Publisher.EqusSipXpsx: value = Publisher.EqusSipXpsx; return true;
            case (ushort)Publisher.EqusSipBaty: value = Publisher.EqusSipBaty; return true;
            case (ushort)Publisher.EqusSipBats: value = Publisher.EqusSipBats; return true;
            case (ushort)Publisher.EqusSipFinn: value = Publisher.EqusSipFinn; return true;
            case (ushort)Publisher.EqusSipFiny: value = Publisher.EqusSipFiny; return true;
            case (ushort)Publisher.EqusSipFinc: value = Publisher.EqusSipFinc; return true;
            case (ushort)Publisher.EqusSipXadf: value = Publisher.EqusSipXadf; return true;
            case (ushort)Publisher.EqusSipCta: value = Publisher.EqusSipCta; return true;
            case (ushort)Publisher.EqusSipUtp: value = Publisher.EqusSipUtp; return true;
            case (ushort)Publisher.MsciCgifMsci: value = Publisher.MsciCgifMsci; return true;
            case (ushort)Publisher.FtseCgifFtse: value = Publisher.FtseCgifFtse; return true;
            case (ushort)Publisher.InavCgifInav: value = Publisher.InavCgifInav; return true;
            case (ushort)Publisher.MstarCgifMstar: value = Publisher.MstarCgifMstar; return true;
            case (ushort)Publisher.CccyCgifCccy: value = Publisher.CccyCgifCccy; return true;
            case (ushort)Publisher.CgiCgifCgi: value = Publisher.CgiCgifCgi; return true;
            case (ushort)Publisher.MainCgifDef: value = Publisher.MainCgifDef; return true;
            case (ushort)Publisher.XtksFlexXtks: value = Publisher.XtksFlexXtks; return true;
            case (ushort)Publisher.XtktItchXtkt: value = Publisher.XtktItchXtkt; return true;
            case (ushort)Publisher.XoseItchXose: value = Publisher.XoseItchXose; return true;
            default: value = default; return false;
        }
    }

    // ---------------- Dataset

    /// <summary>Tries to validate <paramref name="raw"/> as a defined <see cref="Dataset"/>.</summary>
    /// <param name="raw">The raw wire word.</param>
    /// <param name="value">The validated <see cref="Dataset"/>, or <see langword="default"/> when <paramref name="raw"/> is not one.</param>
    /// <returns><see langword="true"/> when <paramref name="raw"/> is a defined <see cref="Dataset"/>.</returns>
    public static bool TryFromDataset(ushort raw, out Dataset value)
    {
        switch (raw)
        {
            case (ushort)Dataset.GlbxMdp3: value = Dataset.GlbxMdp3; return true;
            case (ushort)Dataset.XnasItch: value = Dataset.XnasItch; return true;
            case (ushort)Dataset.XbosItch: value = Dataset.XbosItch; return true;
            case (ushort)Dataset.XpsxItch: value = Dataset.XpsxItch; return true;
            case (ushort)Dataset.BatsPitch: value = Dataset.BatsPitch; return true;
            case (ushort)Dataset.BatyPitch: value = Dataset.BatyPitch; return true;
            case (ushort)Dataset.EdgaPitch: value = Dataset.EdgaPitch; return true;
            case (ushort)Dataset.EdgxPitch: value = Dataset.EdgxPitch; return true;
            case (ushort)Dataset.XnysPillar: value = Dataset.XnysPillar; return true;
            case (ushort)Dataset.XcisPillar: value = Dataset.XcisPillar; return true;
            case (ushort)Dataset.XasePillar: value = Dataset.XasePillar; return true;
            case (ushort)Dataset.XchiPillar: value = Dataset.XchiPillar; return true;
            case (ushort)Dataset.XcisBbo: value = Dataset.XcisBbo; return true;
            case (ushort)Dataset.XcisTrades: value = Dataset.XcisTrades; return true;
            case (ushort)Dataset.MemxMemoir: value = Dataset.MemxMemoir; return true;
            case (ushort)Dataset.EprlDom: value = Dataset.EprlDom; return true;
            case (ushort)Dataset.FinnNls: value = Dataset.FinnNls; return true;
            case (ushort)Dataset.FinyTrades: value = Dataset.FinyTrades; return true;
            case (ushort)Dataset.OpraPillar: value = Dataset.OpraPillar; return true;
            case (ushort)Dataset.DbeqBasic: value = Dataset.DbeqBasic; return true;
            case (ushort)Dataset.ArcxPillar: value = Dataset.ArcxPillar; return true;
            case (ushort)Dataset.IexgTops: value = Dataset.IexgTops; return true;
            case (ushort)Dataset.EqusPlus: value = Dataset.EqusPlus; return true;
            case (ushort)Dataset.XnysBbo: value = Dataset.XnysBbo; return true;
            case (ushort)Dataset.XnysTrades: value = Dataset.XnysTrades; return true;
            case (ushort)Dataset.XnasQbbo: value = Dataset.XnasQbbo; return true;
            case (ushort)Dataset.XnasNls: value = Dataset.XnasNls; return true;
            case (ushort)Dataset.IfeuImpact: value = Dataset.IfeuImpact; return true;
            case (ushort)Dataset.NdexImpact: value = Dataset.NdexImpact; return true;
            case (ushort)Dataset.EqusAll: value = Dataset.EqusAll; return true;
            case (ushort)Dataset.XnasBasic: value = Dataset.XnasBasic; return true;
            case (ushort)Dataset.EqusSummary: value = Dataset.EqusSummary; return true;
            case (ushort)Dataset.XcisTradesbbo: value = Dataset.XcisTradesbbo; return true;
            case (ushort)Dataset.XnysTradesbbo: value = Dataset.XnysTradesbbo; return true;
            case (ushort)Dataset.EqusMini: value = Dataset.EqusMini; return true;
            case (ushort)Dataset.IfusImpact: value = Dataset.IfusImpact; return true;
            case (ushort)Dataset.IfllImpact: value = Dataset.IfllImpact; return true;
            case (ushort)Dataset.XeurEobi: value = Dataset.XeurEobi; return true;
            case (ushort)Dataset.XeeeEobi: value = Dataset.XeeeEobi; return true;
            case (ushort)Dataset.XcbfPitch: value = Dataset.XcbfPitch; return true;
            case (ushort)Dataset.OceaMemoir: value = Dataset.OceaMemoir; return true;
            case (ushort)Dataset.MainCgif: value = Dataset.MainCgif; return true;
            case (ushort)Dataset.EqusSip: value = Dataset.EqusSip; return true;
            case (ushort)Dataset.MsciCgif: value = Dataset.MsciCgif; return true;
            case (ushort)Dataset.FtseCgif: value = Dataset.FtseCgif; return true;
            case (ushort)Dataset.InavCgif: value = Dataset.InavCgif; return true;
            case (ushort)Dataset.MstarCgif: value = Dataset.MstarCgif; return true;
            case (ushort)Dataset.CccyCgif: value = Dataset.CccyCgif; return true;
            case (ushort)Dataset.CgiCgif: value = Dataset.CgiCgif; return true;
            case (ushort)Dataset.XtksFlex: value = Dataset.XtksFlex; return true;
            case (ushort)Dataset.XtktItch: value = Dataset.XtktItch; return true;
            case (ushort)Dataset.XoseItch: value = Dataset.XoseItch; return true;
            default: value = default; return false;
        }
    }

    // ---------------- Venue

    /// <summary>Tries to validate <paramref name="raw"/> as a defined <see cref="Venue"/>.</summary>
    /// <param name="raw">The raw wire word.</param>
    /// <param name="value">The validated <see cref="Venue"/>, or <see langword="default"/> when <paramref name="raw"/> is not one.</param>
    /// <returns><see langword="true"/> when <paramref name="raw"/> is a defined <see cref="Venue"/>.</returns>
    public static bool TryFromVenue(ushort raw, out Venue value)
    {
        switch (raw)
        {
            case (ushort)Venue.Glbx: value = Venue.Glbx; return true;
            case (ushort)Venue.Xnas: value = Venue.Xnas; return true;
            case (ushort)Venue.Xbos: value = Venue.Xbos; return true;
            case (ushort)Venue.Xpsx: value = Venue.Xpsx; return true;
            case (ushort)Venue.Bats: value = Venue.Bats; return true;
            case (ushort)Venue.Baty: value = Venue.Baty; return true;
            case (ushort)Venue.Edga: value = Venue.Edga; return true;
            case (ushort)Venue.Edgx: value = Venue.Edgx; return true;
            case (ushort)Venue.Xnys: value = Venue.Xnys; return true;
            case (ushort)Venue.Xcis: value = Venue.Xcis; return true;
            case (ushort)Venue.Xase: value = Venue.Xase; return true;
            case (ushort)Venue.Arcx: value = Venue.Arcx; return true;
            case (ushort)Venue.Xchi: value = Venue.Xchi; return true;
            case (ushort)Venue.Iexg: value = Venue.Iexg; return true;
            case (ushort)Venue.Finn: value = Venue.Finn; return true;
            case (ushort)Venue.Finc: value = Venue.Finc; return true;
            case (ushort)Venue.Finy: value = Venue.Finy; return true;
            case (ushort)Venue.Memx: value = Venue.Memx; return true;
            case (ushort)Venue.Eprl: value = Venue.Eprl; return true;
            case (ushort)Venue.Amxo: value = Venue.Amxo; return true;
            case (ushort)Venue.Xbox: value = Venue.Xbox; return true;
            case (ushort)Venue.Xcbo: value = Venue.Xcbo; return true;
            case (ushort)Venue.Emld: value = Venue.Emld; return true;
            case (ushort)Venue.Edgo: value = Venue.Edgo; return true;
            case (ushort)Venue.Gmni: value = Venue.Gmni; return true;
            case (ushort)Venue.Xisx: value = Venue.Xisx; return true;
            case (ushort)Venue.Mcry: value = Venue.Mcry; return true;
            case (ushort)Venue.Xmio: value = Venue.Xmio; return true;
            case (ushort)Venue.Arco: value = Venue.Arco; return true;
            case (ushort)Venue.Opra: value = Venue.Opra; return true;
            case (ushort)Venue.Mprl: value = Venue.Mprl; return true;
            case (ushort)Venue.Xndq: value = Venue.Xndq; return true;
            case (ushort)Venue.Xbxo: value = Venue.Xbxo; return true;
            case (ushort)Venue.C2Ox: value = Venue.C2Ox; return true;
            case (ushort)Venue.Xphl: value = Venue.Xphl; return true;
            case (ushort)Venue.Bato: value = Venue.Bato; return true;
            case (ushort)Venue.Mxop: value = Venue.Mxop; return true;
            case (ushort)Venue.Ifeu: value = Venue.Ifeu; return true;
            case (ushort)Venue.Ndex: value = Venue.Ndex; return true;
            case (ushort)Venue.Dbeq: value = Venue.Dbeq; return true;
            case (ushort)Venue.Sphr: value = Venue.Sphr; return true;
            case (ushort)Venue.Ltse: value = Venue.Ltse; return true;
            case (ushort)Venue.Xoff: value = Venue.Xoff; return true;
            case (ushort)Venue.Aspn: value = Venue.Aspn; return true;
            case (ushort)Venue.Asmt: value = Venue.Asmt; return true;
            case (ushort)Venue.Aspi: value = Venue.Aspi; return true;
            case (ushort)Venue.Equs: value = Venue.Equs; return true;
            case (ushort)Venue.Ifus: value = Venue.Ifus; return true;
            case (ushort)Venue.Ifll: value = Venue.Ifll; return true;
            case (ushort)Venue.Xeur: value = Venue.Xeur; return true;
            case (ushort)Venue.Xeee: value = Venue.Xeee; return true;
            case (ushort)Venue.Xcbf: value = Venue.Xcbf; return true;
            case (ushort)Venue.Ocea: value = Venue.Ocea; return true;
            case (ushort)Venue.Mxto: value = Venue.Mxto; return true;
            case (ushort)Venue.Iexo: value = Venue.Iexo; return true;
            case (ushort)Venue.Main: value = Venue.Main; return true;
            case (ushort)Venue.Txse: value = Venue.Txse; return true;
            case (ushort)Venue._24Eq: value = Venue._24Eq; return true;
            case (ushort)Venue.Cta: value = Venue.Cta; return true;
            case (ushort)Venue.Utp: value = Venue.Utp; return true;
            case (ushort)Venue.Xadf: value = Venue.Xadf; return true;
            case (ushort)Venue.Msci: value = Venue.Msci; return true;
            case (ushort)Venue.Ftse: value = Venue.Ftse; return true;
            case (ushort)Venue.Inav: value = Venue.Inav; return true;
            case (ushort)Venue.Mstar: value = Venue.Mstar; return true;
            case (ushort)Venue.Cccy: value = Venue.Cccy; return true;
            case (ushort)Venue.Cgi: value = Venue.Cgi; return true;
            case (ushort)Venue.Def: value = Venue.Def; return true;
            case (ushort)Venue.Xtks: value = Venue.Xtks; return true;
            case (ushort)Venue.Xtkt: value = Venue.Xtkt; return true;
            case (ushort)Venue.Xose: value = Venue.Xose; return true;
            default: value = default; return false;
        }
    }
}
