// <auto-generated>
//   Generated by tools/generate-publishers.py from the `dbn` crate's publishers.rs
//   (crate version 0.68.0). Do not hand-edit.
//   Regenerate with: python3 tools/generate-publishers.py <path-to-publishers.rs>
// </auto-generated>

#nullable enable

namespace DatabentoDotNet.Dbn.Publishers;

/// <summary>A trading execution venue.</summary>
/// <remarks>
/// Mechanically derived from the <c>dbn</c> crate's <c>publishers.rs</c> (v0.68.0) by <c>tools/generate-publishers.py</c>. 71 variants, contiguous <c>1..71</c>. Upstream marks this type <c>#[non_exhaustive]</c>; there is no default (zero) variant. See <see cref="PublisherWireStrings"/> for wire-string conversions.
/// </remarks>
public enum Venue : ushort
{
    /// <summary>CME Globex</summary>
    Glbx = 1,

    /// <summary>Nasdaq - All Markets</summary>
    Xnas = 2,

    /// <summary>Nasdaq OMX BX</summary>
    Xbos = 3,

    /// <summary>Nasdaq OMX PSX</summary>
    Xpsx = 4,

    /// <summary>Cboe BZX U.S. Equities Exchange</summary>
    Bats = 5,

    /// <summary>Cboe BYX U.S. Equities Exchange</summary>
    Baty = 6,

    /// <summary>Cboe EDGA U.S. Equities Exchange</summary>
    Edga = 7,

    /// <summary>Cboe EDGX U.S. Equities Exchange</summary>
    Edgx = 8,

    /// <summary>New York Stock Exchange, Inc.</summary>
    Xnys = 9,

    /// <summary>NYSE National, Inc.</summary>
    Xcis = 10,

    /// <summary>NYSE MKT LLC</summary>
    Xase = 11,

    /// <summary>NYSE Arca</summary>
    Arcx = 12,

    /// <summary>NYSE Texas, Inc.</summary>
    Xchi = 13,

    /// <summary>Investors Exchange</summary>
    Iexg = 14,

    /// <summary>FINRA/Nasdaq TRF Carteret</summary>
    Finn = 15,

    /// <summary>FINRA/Nasdaq TRF Chicago</summary>
    Finc = 16,

    /// <summary>FINRA/NYSE TRF</summary>
    Finy = 17,

    /// <summary>MEMX LLC Equities</summary>
    Memx = 18,

    /// <summary>MIAX Pearl Equities</summary>
    Eprl = 19,

    /// <summary>NYSE American Options</summary>
    Amxo = 20,

    /// <summary>BOX Options</summary>
    Xbox = 21,

    /// <summary>Cboe Options</summary>
    Xcbo = 22,

    /// <summary>MIAX Emerald</summary>
    Emld = 23,

    /// <summary>Cboe EDGX Options</summary>
    Edgo = 24,

    /// <summary>Nasdaq GEMX</summary>
    Gmni = 25,

    /// <summary>Nasdaq ISE</summary>
    Xisx = 26,

    /// <summary>Nasdaq MRX</summary>
    Mcry = 27,

    /// <summary>MIAX Options</summary>
    Xmio = 28,

    /// <summary>NYSE Arca Options</summary>
    Arco = 29,

    /// <summary>Options Price Reporting Authority</summary>
    Opra = 30,

    /// <summary>MIAX Pearl</summary>
    Mprl = 31,

    /// <summary>Nasdaq Options</summary>
    Xndq = 32,

    /// <summary>Nasdaq Texas Options</summary>
    Xbxo = 33,

    /// <summary>Cboe C2 Options</summary>
    C2Ox = 34,

    /// <summary>Nasdaq PHLX</summary>
    Xphl = 35,

    /// <summary>Cboe BZX Options</summary>
    Bato = 36,

    /// <summary>MEMX Options</summary>
    Mxop = 37,

    /// <summary>ICE Europe Commodities</summary>
    Ifeu = 38,

    /// <summary>ICE Endex</summary>
    Ndex = 39,

    /// <summary>Databento US Equities - Consolidated</summary>
    Dbeq = 40,

    /// <summary>MIAX Sapphire</summary>
    Sphr = 41,

    /// <summary>Long-Term Stock Exchange, Inc.</summary>
    Ltse = 42,

    /// <summary>Off-Exchange Transactions - Listed Instruments</summary>
    Xoff = 43,

    /// <summary>IntelligentCross ASPEN Intelligent Bid/Offer</summary>
    Aspn = 44,

    /// <summary>IntelligentCross ASPEN Maker/Taker</summary>
    Asmt = 45,

    /// <summary>IntelligentCross ASPEN Inverted</summary>
    Aspi = 46,

    /// <summary>Databento US Equities - Consolidated</summary>
    Equs = 47,

    /// <summary>ICE Futures US</summary>
    Ifus = 48,

    /// <summary>ICE Europe Financials</summary>
    Ifll = 49,

    /// <summary>Eurex Exchange</summary>
    Xeur = 50,

    /// <summary>European Energy Exchange</summary>
    Xeee = 51,

    /// <summary>Cboe Futures Exchange</summary>
    Xcbf = 52,

    /// <summary>Blue Ocean ATS</summary>
    Ocea = 53,

    /// <summary>MX2 Options</summary>
    Mxto = 54,

    /// <summary>IEX Options LLC</summary>
    Iexo = 55,

    /// <summary>Cboe Global Indices Feed</summary>
    Main = 56,

    /// <summary>Texas Stock Exchange, LLC</summary>
    Txse = 57,

    /// <summary>24X National Exchange, LLC</summary>
    _24Eq = 58,

    /// <summary>Consolidated Tape Association</summary>
    Cta = 59,

    /// <summary>Unlisted Trading Privileges</summary>
    Utp = 60,

    /// <summary>FINRA Alternative Display Facility</summary>
    Xadf = 61,

    /// <summary>CGIF Morgan Stanley Capital International</summary>
    Msci = 62,

    /// <summary>CGIF FTSE Russell</summary>
    Ftse = 63,

    /// <summary>CGIF Intraday Net Asset Values</summary>
    Inav = 64,

    /// <summary>CGIF Morning Star</summary>
    Mstar = 65,

    /// <summary>CGIF Crypto Currency</summary>
    Cccy = 66,

    /// <summary>CGIF CBOE Global Indices</summary>
    Cgi = 67,

    /// <summary>CGIF Definitions</summary>
    Def = 68,

    /// <summary>Tokyo Stock Exchange</summary>
    Xtks = 69,

    /// <summary>Tokyo Commodity Exchange</summary>
    Xtkt = 70,

    /// <summary>Osaka Exchange</summary>
    Xose = 71,
}
