using System.Text.Json;
using System.Text.Json.Serialization;
using DatabentoDotNet.Dbn;
using DatabentoDotNet.Dbn.Publishers;
using DatabentoDotNet.Historical.Json;
using NodaTime;
using Xunit;

namespace DatabentoDotNet.Historical.Tests;

/// <summary>
/// Each <c>metadata.*</c> response type, read from a body shaped the way Databento documents it.
/// </summary>
/// <remarks>
/// The bodies here are hand-written rather than recorded, and that is the weakness of this file:
/// they and the DTOs were written from the same reading of the same source, so a misread key name
/// would sit in both and they would agree. #40's opt-in tests against the real API are what settle
/// it. What these tests <em>can</em> settle is everything downstream of the key names — the
/// converters, the naming policy, the nullable case, and the two renames.
/// </remarks>
public sealed partial class MetadataResponseTests
{
    [JsonSourceGenerationOptions(
        PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower,
        Converters = [
            typeof(SchemaJsonConverter),
            typeof(FeedModeJsonConverter),
            typeof(DatasetConditionJsonConverter),
            typeof(InstantJsonConverter),
            typeof(LocalDateJsonConverter),
            typeof(DateTimeRangeJsonConverter),
        ])]
    [JsonSerializable(typeof(List<PublisherDetail>))]
    [JsonSerializable(typeof(List<string>))]
    [JsonSerializable(typeof(List<FieldDetail>))]
    [JsonSerializable(typeof(List<UnitPricesForMode>))]
    [JsonSerializable(typeof(List<DatasetConditionDetail>))]
    [JsonSerializable(typeof(DatasetRange))]
    [JsonSerializable(typeof(ulong))]
    [JsonSerializable(typeof(decimal))]
    // Named ResponseJson rather than the brief's Json: System.Text.Json's source generator keys
    // its generated per-type file names off the context class's simple name, not its fully
    // qualified name, so a second nested class also named Json -- MetadataJsonConverterTests.Json,
    // a few files over, which this one also needs a Decimal file for -- collides on
    // "Json.Decimal.g.cs" with CS8785 ("must be unique within a generator") even though the two
    // classes are nested in different outer types. Confirmed by renaming: the build goes green
    // with no other change.
    private sealed partial class ResponseJson : JsonSerializerContext
    {
    }

    [Fact]
    public void PublisherDetail_ReadsAllFourFields()
    {
        var actual = JsonSerializer.Deserialize(
            """
            [{"publisher_id":1,"dataset":"GLBX.MDP3","venue":"GLBX","description":"CME Globex MDP 3.0"}]
            """,
            ResponseJson.Default.ListPublisherDetail);

        var only = Assert.Single(actual!);
        Assert.Equal(1, only.PublisherId);
        Assert.Equal("GLBX.MDP3", only.Dataset);
        Assert.Equal("GLBX", only.Venue);
        Assert.Equal("CME Globex MDP 3.0", only.Description);
    }

    /// <summary>
    /// <para>
    /// The issue asks for this, and its stated reason is wrong in a way worth correcting. It says
    /// <c>list_publishers</c> "is the live truth those tables were generated from". It is not:
    /// every file in <c>src/DatabentoDotNet.Dbn/Publishers/</c> says it was generated by
    /// <c>tools/generate-publishers.py</c> from the <c>dbn</c> crate's <c>publishers.rs</c> at
    /// version 0.68.0.
    /// </para>
    /// <para>
    /// That makes the instruction more right rather than less. The table is pinned to a crate
    /// release, not tracking the API, so a publisher the API returns that the table cannot name is
    /// Databento shipping something after 0.68.0 — their news, not our bug. So the mapping is
    /// offered and never enforced: <c>PublisherDetail</c> keeps the raw <c>ushort</c> and the raw
    /// strings, and a caller who wants the enum asks for it and handles the answer.
    /// </para>
    /// </summary>
    [Fact]
    public void PublisherDetail_MapsOntoTheGeneratedTables_WithoutFailingWhenItCannot()
    {
        var known = new PublisherDetail
        {
            PublisherId = 1, Dataset = "GLBX.MDP3", Venue = "GLBX", Description = "CME Globex MDP 3.0",
        };
        Assert.True(PublisherValues.TryFromPublisher(known.PublisherId, out var publisher));
        Assert.Equal(Publisher.GlbxMdp3Glbx, publisher);
        Assert.True(PublisherWireStrings.TryParseDataset(known.Dataset, out var dataset));
        Assert.Equal(Dataset.GlbxMdp3, dataset);
        Assert.True(PublisherWireStrings.TryParseVenue(known.Venue, out var venue));
        Assert.Equal(Venue.Glbx, venue);

        var unknown = new PublisherDetail
        {
            PublisherId = 60_000, Dataset = "XXXX.FUTURE", Venue = "XXXX", Description = "Added after 0.68.0",
        };
        Assert.False(PublisherValues.TryFromPublisher(unknown.PublisherId, out _));
        Assert.False(PublisherWireStrings.TryParseDataset(unknown.Dataset, out _));
        Assert.False(PublisherWireStrings.TryParseVenue(unknown.Venue, out _));
    }

    [Fact]
    public void FieldDetail_ReadsTypeFromTheKeyNamedType()
    {
        var actual = JsonSerializer.Deserialize(
            """[{"name":"ts_recv","type":"uint64_t"}]""", ResponseJson.Default.ListFieldDetail);

        var only = Assert.Single(actual!);
        Assert.Equal("ts_recv", only.Name);
        Assert.Equal("uint64_t", only.TypeName);
    }

    /// <summary>
    /// The prices are <see langword="decimal"/>, not <see langword="double"/>. Upstream is
    /// <c>f64</c> (<c>metadata.rs:274</c>) because Rust's std has no decimal type; a unit price is
    /// multiplied by a record count before anyone sees a dollar figure, so binary floating point
    /// is a money bug waiting for a large enough request.
    /// </summary>
    [Fact]
    public void UnitPricesForMode_ReadsPricesAsDecimal_KeyedByWireString()
    {
        var actual = JsonSerializer.Deserialize(
            """
            [{"mode":"historical-streaming","unit_prices":{"mbo":0.0000019,"ohlcv-1s":0.0000032}}]
            """,
            ResponseJson.Default.ListUnitPricesForMode);

        var only = Assert.Single(actual!);
        Assert.Equal(FeedMode.HistoricalStreaming, only.Mode);
        Assert.Equal(0.0000019m, only.UnitPrices[Schema.Mbo]);
        Assert.Equal(0.0000032m, only.UnitPrices[Schema.Ohlcv1S]);
    }

    /// <summary>
    /// The issue's gap case: a range spanning days with no data must return a row for every date,
    /// including the empty ones, because a caller asking "is this range complete" gets a wrong
    /// answer from a response that silently omits them. Nothing in the client can create the
    /// missing rows — what it can do is carry every row the API sends, including the one whose
    /// <c>last_modified_date</c> is null.
    /// </summary>
    [Fact]
    public void DatasetConditionDetail_ReadsEveryDayInTheRange_IncludingOneWithNoData()
    {
        var actual = JsonSerializer.Deserialize(
            """
            [{"date":"2023-06-14","condition":"available","last_modified_date":"2023-06-15"},
             {"date":"2023-06-15","condition":"degraded","last_modified_date":"2023-06-16"},
             {"date":"2023-06-16","condition":"missing","last_modified_date":null},
             {"date":"2023-06-17","condition":"pending","last_modified_date":null}]
            """,
            ResponseJson.Default.ListDatasetConditionDetail);

        Assert.Equal(4, actual!.Count);
        Assert.Equal(new LocalDate(2023, 6, 14), actual[0].Date);
        Assert.Equal(DatasetCondition.Available, actual[0].Condition);
        Assert.Equal(new LocalDate(2023, 6, 15), actual[0].LastModifiedDate);
        Assert.Equal(DatasetCondition.Missing, actual[2].Condition);
        Assert.Null(actual[2].LastModifiedDate);
        Assert.Equal(DatasetCondition.Pending, actual[3].Condition);
        Assert.Null(actual[3].LastModifiedDate);
    }

    [Fact]
    public void DatasetRange_ReadsItsSchemaMapFromTheKeyNamedSchema()
    {
        var actual = JsonSerializer.Deserialize(
            """
            {"start":"2023-06-14T00:00:00.000000000Z",
             "end":"2024-01-01T00:00:00.000000000Z",
             "schema":{"trades":{"start":"2023-06-14T00:00:00Z","end":"2024-01-01T00:00:00Z"},
                       "ohlcv-1s":{"start":"2023-07-01T00:00:00Z","end":"2024-01-01T00:00:00Z"}}}
            """,
            ResponseJson.Default.DatasetRange);

        Assert.Equal(Instant.FromUtc(2023, 6, 14, 0, 0, 0), actual!.Start);
        Assert.Equal(Instant.FromUtc(2024, 1, 1, 0, 0, 0), actual.End);
        Assert.Equal(2, actual.RangeBySchema.Count);
        Assert.Equal(Instant.FromUtc(2023, 7, 1, 0, 0, 0), actual.RangeBySchema[Schema.Ohlcv1S].Start);
    }

    /// <summary>Upstream's <c>From&lt;DatasetRange&gt; for DateTimeRange</c>, <c>metadata.rs:320-324</c>.</summary>
    [Fact]
    public void DatasetRange_NarrowsToItsOwnTopLevelRange()
    {
        var range = JsonSerializer.Deserialize(
            """{"start":"2023-06-14T00:00:00Z","end":"2024-01-01T00:00:00Z","schema":{}}""",
            ResponseJson.Default.DatasetRange);

        var actual = range!.ToDateTimeRange();

        Assert.Equal(Instant.FromUtc(2023, 6, 14, 0, 0, 0), actual.Start);
        Assert.Equal(Instant.FromUtc(2024, 1, 1, 0, 0, 0), actual.End);
    }

    [Fact]
    public void BareScalarBodies_ReadAsTheirScalar()
    {
        Assert.Equal(123_456_789UL, JsonSerializer.Deserialize("123456789", ResponseJson.Default.UInt64));
        Assert.Equal(0.65m, JsonSerializer.Deserialize("0.65", ResponseJson.Default.Decimal));
        Assert.Equal(
            ["GLBX.MDP3", "XNAS.ITCH"],
            JsonSerializer.Deserialize("""["GLBX.MDP3","XNAS.ITCH"]""", ResponseJson.Default.ListString));
    }
}
