// <auto-generated>
//   Generated by tools/generate-reference-codes.py from the vendored reference API responses
//   (corporate_actions.list_enums.json and corporate_actions.list_events.json). Do not hand-edit.
//   Regenerate with: python3 tools/generate-reference-codes.py tests/DatabentoDotNet.Reference.Tests/Data
// </auto-generated>

#nullable enable

using System.Collections.Frozen;
using System.Text.Json.Serialization;
using DatabentoDotNet.Reference.Json;

namespace DatabentoDotNet.Reference;

/// <summary>
/// The level a corporate-action event applies at.
/// </summary>
/// <remarks>
/// <para>
/// <b>An open set: a code this library does not know is carried, not lost.</b> Upstream ends
/// this enum in an <c>Unknown(String)</c> variant (<c>enums.rs:2301</c>) so a code Databento adds
/// next month round-trips untouched, and a C# <c>enum</c> cannot hold a payload. See
/// <see cref="IReferenceCode{TSelf}"/> for the shape this takes instead and why.
/// </para>
/// <para>
/// <c>corporate_actions.list_enums</c> has no group for this type, so <c>corporate_actions.list_events</c> is its only authority — and the two agree exactly, upstream included.
/// </para>
/// </remarks>
[JsonConverter(typeof(ReferenceCodeJsonConverter<EventLevel>))]
public readonly record struct EventLevel : IReferenceCode<EventLevel>
{
    private static readonly FrozenSet<string> Codes = FrozenSet.ToFrozenSet(
    [
        "country",
        "issuer",
        "listing",
        "security",
    ], StringComparer.Ordinal);

    private readonly string? _code;

    /// <summary>
    /// Wraps a wire code, known or not. Prefer a named member such as
    /// <see cref="Country"/> where one exists, and <see cref="From"/> where the value came
    /// from the server.
    /// </summary>
    /// <param name="code">The wire code.</param>
    /// <exception cref="ArgumentException"><paramref name="code"/> is null or empty. A blank code is the absence of a value, which is <see langword="default"/>.</exception>
    public EventLevel(string code)
    {
        ArgumentException.ThrowIfNullOrEmpty(code);
        _code = code;
    }

    /// <summary>
    /// Every code the reference API reported for this type when the fixture was captured —
    /// 4 of them.
    /// </summary>
    public static IReadOnlySet<string> KnownCodes => Codes;

    /// <inheritdoc/>
    public string? Code => _code;

    /// <inheritdoc/>
    public bool HasValue => _code is not null;

    /// <inheritdoc/>
    public bool IsKnown => _code is not null && Codes.Contains(_code);

    /// <summary>
    /// Reads a wire code, mapping <see langword="null"/> and the empty string to
    /// <see langword="default"/> — the absence of a value.
    /// </summary>
    /// <param name="code">The wire code, or <see langword="null"/>.</param>
    /// <returns>The value.</returns>
    public static EventLevel From(string? code) => string.IsNullOrEmpty(code) ? default : new(code);

    /// <summary>The wire code, or the empty string when this names no value.</summary>
    /// <returns>The wire code.</returns>
    public override string ToString() => _code ?? string.Empty;

    /// <summary>country (<c>country</c>).</summary>
    public static EventLevel Country => new("country");

    /// <summary>issuer (<c>issuer</c>).</summary>
    public static EventLevel Issuer => new("issuer");

    /// <summary>listing (<c>listing</c>).</summary>
    public static EventLevel Listing => new("listing");

    /// <summary>security (<c>security</c>).</summary>
    public static EventLevel Security => new("security");
}
